# Generated by Django 4.1.3 on 2022-12-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.URLField()),
                ('job', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(blank=True, default='1')),
                ('name', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('pantone_value', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_API.group')),
            ],
        ),
        migrations.CreateModel(
            name='RequestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.people')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.group')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.people')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.people')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ManyToManyField(related_name='leader', to='app_API.people'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='app_API.Membership', to='app_API.people'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_API.people')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to='app_API.people')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app_API.people')),
                ('users1', models.ManyToManyField(to='app_API.people')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=1500)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_API.people')),
            ],
        ),
    ]
